// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-EugJi1MyqWe4l8G4DqtjykEeqnevsT8',
    appId: '1:443484865448:web:dffd1d739cceccf25c539d',
    messagingSenderId: '443484865448',
    projectId: 'meteo-board',
    authDomain: 'meteo-board.firebaseapp.com',
    storageBucket: 'meteo-board.appspot.com',
    measurementId: 'G-7GCWGR3SVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY0cu67hMFb_5BHj3iG9afj73d_7UMSY0',
    appId: '1:443484865448:android:896502083b5ab60d5c539d',
    messagingSenderId: '443484865448',
    projectId: 'meteo-board',
    storageBucket: 'meteo-board.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtgMdecbtsvfeUFxCMw9GzJ1hlwgoRWg8',
    appId: '1:443484865448:ios:2616959ce13fc6615c539d',
    messagingSenderId: '443484865448',
    projectId: 'meteo-board',
    storageBucket: 'meteo-board.appspot.com',
    iosBundleId: 'com.example.clientAppFlutter',
  );
}
